config/routes.rb
Rails.application.routes.draw do

  root 'authorities#index'

  resources :authorities

end

app/models/authorities.rb
class Authorities
  include Mongoid::Document

  field :username, type: String
  field :avatar, type: String

  has_many :repos
end

app/models/authority.rb
class Authority
  include Mongoid::Document
  include Mongoid::Slug

  field :username, type: String
  field :name, type: String
  field :avatar, type: String

  has_many :repos
  slug :username
end

app/models/repo.rb
class Repo
  include Mongoid::Document

  field :name, type: String
  field :description, type: String
  field :url, type: String
  field :created, type: DateTime
  field :language, type: String
  field :commits, type: Integer
  field :stars, type: Integer
  field :forks, type: Integer
  field :issues, type: Integer
  field :contributors, type: Array
  field :civic_present?, type: Boolean
  field :thumbnail, type: String
  field :status, type: String
  field :owner, type: Hash
  field :deployments, type: Array
  field :service_categories, type: Array
  field :technologies, type: Array

  belongs_to :authority

  def commit_link
    "#{url}/commits/master"
  end

  def stars_link
    "#{url}/stargazers"
  end

  def forks_link
    "#{url}/network"
  end

  def issues_link
    "#{url}/issues"
  end
end

app/models/repos.rb
class Repos
  include Mongoid::Document

  field :name, type: String
  field :description, type: String
  field :url, type: String
  field :civic_present?, type: Boolean
  field :thumbnail, type: String
  field :status, type: String
  field :owner, type: Array
  field :service_categories, type: Array
  field :technologies, type: Array

  belongs_to :authorties
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authorities_controller.rb
class AuthoritiesController < ApplicationController

  def index
    @authorities = Authority.all.order_by(:name.asc)
  end

  def show
    @authority = Authority.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorities_helper.rb
module AuthoritiesHelper
end

app/views/authorities/_repo.html.erb
<tr class="repo">
  <td>
    <h3><%= link_to repo.name, repo.url %></h3>
    <%= image_tag repo.thumbnail, height: 100, alt: repo.name, class: "pull-left" unless repo.thumbnail.blank? %>
    <p><strong>Created:</strong> <%= time_ago_in_words repo.created %> ago</p>
    <p><strong>Language:</strong> <%= repo.language || "Unknown" %></p>

  </td>

  <td>
    <p><%= repo.description %></p>
    <h4>Contributors</h4>
    <% repo.contributors.each do |c| %>
      <%= link_to image_tag(c["avatar_url"] + "s=48", alt: c["name"], width: 48, height: 48, class: "img-thumbnail"), c["url"] %>
    <% end %>
    <% if repo.civic_present? %>
      <p><strong>Status:</strong> <span class="label label-primary"><%= repo.status %></span></p>
      <p><strong>Owner:</strong> <span class="label label-success"><%= repo.owner['name'] %></span></p>
      <% if repo.service_categories.length > 0 %>
        <p><strong>Service Categories:</strong>
            <% repo.service_categories.each do |s| %>
              <span class="label label-success"><%= s['name'] %></span>
            <% end %>
        </p>
      <% end %>
      <p><strong>Technologies:</strong>
          <% repo.technologies.each do |t| %>
            <span class="label label-success"><%= t['name'] %></span></p>
          <% end %>
      </p>
    <% end %>
  </td>

  <td class="text-center">
    <%= link_to repo.commits, repo.commit_link, class: "btn btn-info" %>
  </td>

  <td class="text-center">
    <%= link_to repo.stars, repo.stars_link, class: "btn btn-info" %>
  </td>

  <td class="text-center">
    <%= link_to repo.forks, repo.forks_link, class: "btn btn-info" %>
  </td>

  <td class="text-center">
    <%= link_to repo.issues, repo.issues_link, class: "btn btn-info" %>
  </td>


</tr>

app/views/authorities/index.html.erb
<div class="jumbotron">
  <h1>LG Projects</h1>
  <p>Find local government code in Github</p>
</div>

  <% @authorities.each do |a| %>
    <div class="media">
      <%= link_to image_tag(a.avatar, width: 64, height: 64, alt: a.name), authority_path(a), class: "pull-left img-thumbnail" %>
      <div class="media-body">
        <h4 class="media-heading"><%= link_to a.name, authority_path(a) %></h4>
      </div>
    </div>
  <% end %>

app/views/authorities/show.html.erb
<div class="row">
  <div class="pull-left">
    <%= image_tag @authority.avatar, width: 80, height: 80, alt: @authority.name, class: "img-thumbnail authority-logo" %>
  </div>
  <h1 id="authority-name"><%= @authority.name || @authority.username %></h1>
</div>

<div class="row">

  <table class="table repos">

    <tr>
      <th scope="col">Project</th>
      <th scope="col">Description</th>
      <th scope="col">Commits</th>
      <th scope="col">Stars</th>
      <th scope="col">Forks</th>
      <th scope="col">Issues</th>
    </tr>

    <% @authority.repos.each do |r| %>
      <%= render partial: "repo", locals: { repo: r } %>
    <% end %>

  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lgprojects" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <a href="https://github.com/pezholio/lg-projects"><img style="position: absolute; top: 0; right: 0; border: 0; z-index: 1001;" src="https://camo.githubusercontent.com/652c5b9acfaddf3a9c326fa6bde407b87f7be0f4/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6f72616e67655f6666373630302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png"></a>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">LG Projects</a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>